Cambios de proveedor cloud

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -63,6 +63,20 @@ jobs:
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
 
+      - name: Restore Ansible Inventory from Cache
+        uses: actions/cache/restore@v4
+        with:
+          path: Ansible/inventory.ini
+          key: ansible-inventory-cache-
+
+      # Verificación de seguridad por si acaso el caché llegara a estar vacío
+      - name: Check Inventory Existence
+        run: |
+          if [ ! -f Ansible/inventory.ini ]; then
+            echo "Error: El archivo Ansible/inventory.ini no está en el caché. Ejecuta el pipeline de Terraform primero."
+            exit 1
+          fi    
+
       - name: Ejecutar Ansible
         env:
           TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
@@ -70,4 +84,7 @@ jobs:
         run: |
           cd Ansible
           ansible-playbook playbook.yml \
-          --private-key ~/.ssh/id_rsa    
+          -i inventory.ini \
+          --private-key ~/.ssh/id_rsa \
+          -e "doppler_token=${DOPPLER_AUTH_TOKEN}" \
+          -e "tailscale_auth_key=${TAILSCALE_AUTH_KEY}"     
